### ISSUE TITLE
Add English OCH Providers

### ISSUE THREAD

**Issue by twayz** [jojo141185/CouchPotatoServer#6]
Hey,

OCH integration into CP sounds like a great idea! I would love to test out this build. But, would you be able to add English OCH providers? Thank you!

**Comment by seppi91** [comment]
What's your favorite one?

**Comment by twayz** [comment]
rslinks.org is pretty good. Thanks man!

**Comment by seppi91** [comment]
If you like to you can give it a try (Branch rslinks):
https://github.com/seppi91/CouchPotatoServer/tree/rslinks

**Comment by twayz** [comment]
thanks man. I tested it and got this error:

[   couchpotato.core.event] Error in event "provider.search.och.movie", that wasn't caught: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(_args, *_kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/och/base.py", line 116, in search
    self._searchOnTitle(title, media, quality, results)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/och/rslinks.py", line 35, in _searchOnTitle
    results.append(result)  # gets cleared if release not matched
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 297, in append
    new_result = self.fillResult(result)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 339, in fillResult
    return mergeDicts(defaults, result)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/helpers/variable.py", line 95, in mergeDicts
    for key in current_src:
TypeError: 'float' object is not iterable
encoding=UTF-8 debug=True args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)

**Comment by seppi91** [comment]
Could you provide some more lines of your log, on my side it works quite well.
